[[redirects]]
  from = "/"
  to = "/en-US"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/nl-NL"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["nl"]}

# Let's see if this works.
[[redirects]]
  from = "/"
  to = "/nl-NL"
  status = 301
  force = false
  query = {path = ":path"}
