on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'

    steps:
    - name: Use Node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - run: pwd
    - name: pwd

    - run: npm install
    - name: installing package.json dependencies
      uses: actions/setup-node@v1

    - run: npm run build
    - name: 🔨 building 11ty site..
      uses: actions/setup-node@v1

    - run: echo ${{ secrets.deploy_username }}
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        local-dir: ./dist
        ftp-server: sftp://sftp.op-de-kop.nl/public/sites/www.op-de-kop.nl
        ftp-username: 198511
        ftp-password: ${{ secrets.deploy_password }}
        git-ftp-args: --insecure
