on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-22.04
    # if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        name: 🚚 Get latest code
      - name: Build
        uses: nielsbom/actions-eleventy@master
      - name: git status
        run: git status -uno --porcelain

      - name: debug
        run: ls -la dist/

      - name: copy files
        run: cp -r dist/* ./

      - name: debug
        run: ls -la ./

      - name: git reset
        run: git reset --hard

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
#          local-dir: ./
          ftp-server: sftp://sftp.op-de-kop.nl/public/sites/www.op-de-kop.nl
          ftp-username: ${{ secrets.deploy_username }}
          ftp-password: ${{ secrets.deploy_password }}
          git-ftp-args: --insecure
