on:
  push:
   branches-ignore:
     - main
name: 🚀 Deploy staging website on push to any branch that is not main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-18.04
    # if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        name: 🚚 Get latest code
      - name: Build
        uses: Rian190/actions-eleventy@patch-2
      - name: git status
        run: git status -uno --porcelain

      - name: debug
        run: ls -la dist/

      - name: copy files
        run: cp -r dist/* ./

      - name: debug
        run: node -v

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
#          local-dir: ./
          ftp-server: sftp://sftp.op-de-kop.nl/public/sites/staging.op-de-kop.nl
          ftp-username: ${{ secrets.deploy_username }}
          ftp-password: ${{ secrets.deploy_password }}
          git-ftp-args: --insecure
